### ISSUE TITLE
Unity Prototype Setup

### ISSUE THREAD

**Issue by wbp1702** [CSG-3613/alt-ctrl-team-4#2]
### Progress
I worked on setting up a basic unity prototype for the project. I downloaded a helicopter model and tree models from the Unity Asset Store. I also added code for basic controls using the keyboard with Unity's new input system.

### Barriers
Using the Ports namespace in C# requires switching to the dot NET framework in the Unity project settings.

### Completed
I completed the Unity project setup and basic code for input controls.

### Next Steps
We plan to split into teams for further work (terrain, input handling, etc.)

**Comment by kimariana** [comment]
Weekly Update: April 15 - 19

## PROGRESS
I created a terrain branch on our Unity project to focus on building the level environment. The helicopter and terrain are viewed in 2D with an orthographic camera. The helicopter will move at a dynamic speed horizontally across the screen as the terrain remains static. I set up basic environment obstacles including trees, rocks, birds with animation, and a fire particle system. We also started creating the game concept document.

Assets:
Helicopter: https://assetstore.unity.com/packages/3d/vehicles/air/low-poly-helicopters-pack-free-121151#description
Nature/Bird: https://assetstore.unity.com/packages/3d/environments/simplistic-low-poly-nature-93894#content

## SLOWDOWNS
The alternate controller has not been built yet, so a proper input system cannot be used to build the level prototype. Although a meeting for the Toy Design members to finish the design for the physical controls was scheduled this week, we did not discuss what inputs we would need with them in person.

## COMPLETED
The basic terrain layout has been built. Temporary controls for the movement of the helicopter and rope were set up in order to test the pacing of where to position the obstacles and people.
